scheb_two_factor:
    security_tokens:
#        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    totp:
        enabled: true
        server_name: 'Ofertilo App'
        issuer: 'Ofertilo by woodflag.eu'
        template: 'security/2fa.html.twig'
#        parameters:
#            image: 'https://my-service/img/logo.png'

    # The service which is used to persist data in the user object. By default Doctrine is used. If your entity is
    # managed by something else (e.g. an API), you have to implement a custom persister
    persister: scheb_two_factor.persister.doctrine

    # If your Doctrine user object is managed by a model manager, which is not the default one, you have to
    # set this option. Name of entity manager or null, which uses the default one.
    model_manager_name: ~