scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        server_name: 'Ofertilo App'
        issuer: 'Ofertilo'
        template: 'security/2fa_form.html.twig'