<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251225105626 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE appuser ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE appuser ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE client ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE client ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN client.created_at IS \'\'');
        $this->addSql('ALTER TABLE color ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE color ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE country ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE country ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE material ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE material ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE material_price ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE material_price ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product_color ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product_color ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE translation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE translation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('CREATE INDEX idx_translation_lookup ON translation (object_class, object_id, locale)');
        $this->addSql('ALTER TABLE wood ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE wood ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE appuser ALTER id SET DEFAULT nextval(\'appuser_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE appuser ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE client ALTER id SET DEFAULT nextval(\'client_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE client ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN client.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE color ALTER id SET DEFAULT nextval(\'color_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE color ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE country ALTER id SET DEFAULT nextval(\'country_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE country ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE material ALTER id SET DEFAULT nextval(\'material_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE material ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE material_price ALTER id SET DEFAULT nextval(\'material_price_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE material_price ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE product ALTER id SET DEFAULT nextval(\'product_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE product_color ALTER id SET DEFAULT nextval(\'product_color_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product_color ALTER id DROP IDENTITY');
        $this->addSql('DROP INDEX idx_translation_lookup');
        $this->addSql('ALTER TABLE translation ALTER id SET DEFAULT nextval(\'translation_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE translation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE wood ALTER id SET DEFAULT nextval(\'wood_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE wood ALTER id DROP IDENTITY');
    }
}
