<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260107105142 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_component (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, length INT NOT NULL, width INT NOT NULL, thickness INT NOT NULL, shape_description TEXT DEFAULT NULL, blueprint_image BYTEA DEFAULT NULL, blueprint_original_name VARCHAR(255) DEFAULT NULL, blueprint_mime_type VARCHAR(100) DEFAULT NULL, product_size_id INT NOT NULL, material_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_275E17DA9854B397 ON product_component (product_size_id)');
        $this->addSql('CREATE INDEX IDX_275E17DAE308AC6F ON product_component (material_id)');
        $this->addSql('CREATE TABLE product_size (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, length INT NOT NULL, width INT NOT NULL, thickness INT DEFAULT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A2806CB4584665A ON product_size (product_id)');
        $this->addSql('ALTER TABLE product_component ADD CONSTRAINT FK_275E17DA9854B397 FOREIGN KEY (product_size_id) REFERENCES product_size (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_component ADD CONSTRAINT FK_275E17DAE308AC6F FOREIGN KEY (material_id) REFERENCES material (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_size ADD CONSTRAINT FK_7A2806CB4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_component DROP CONSTRAINT FK_275E17DA9854B397');
        $this->addSql('ALTER TABLE product_component DROP CONSTRAINT FK_275E17DAE308AC6F');
        $this->addSql('ALTER TABLE product_size DROP CONSTRAINT FK_7A2806CB4584665A');
        $this->addSql('DROP TABLE product_component');
        $this->addSql('DROP TABLE product_size');
    }
}
