name: PHPUnit tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # Pro commit coverage badge
      pages: write       # Pro deployment na GitHub Pages
      id-token: write    # Pro GitHub Pages

    services:
      postgres:
        image: library/postgres:17.5-alpine
        env:
          POSTGRES_DB: ofertilo_test
          POSTGRES_USER: app
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, xdebug
          coverage: xdebug

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-scripts

      - name: Create var directory
        run: mkdir -p var

#      - name: Create test database
#        run: |
#          cp .env .env.test.local
#          echo "DATABASE_URL=postgresql://app:test@127.0.0.1:5432/ofertilo_test" >> .env.test

      - name: Configure test database
        run: |
          touch .env.local
          echo 'APP_ENV=test' > .env.local

      - name: Run database migrations
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run PHPUnit tests with coverage
        run: php bin/phpunit --coverage-clover coverage.xml --coverage-text

      - name: Generate coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/coverage.svg
          push_badge: false

      - name: Push badge to image-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Coverage Check
        uses: ericsizemore/phpunit-coverage-check-action@1.0.0
        with:
          clover_file: 'coverage.xml'
          threshold: 80